# Generated by Django 2.2.3 on 2019-07-12 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Results',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Position', models.CharField(max_length=100)),
                ('Company', models.CharField(max_length=100)),
                ('Salary', models.CharField(max_length=100)),
                ('URL', models.CharField(max_length=1000)),
            ],
        ),
    ]
